name: opendata

services:

  labelct:
    build:
      dockerfile: DockerfileLocalDev
    environment:
      - RUN_MODE=LOCAL
    ports:
      - ${LABEL_CLIENT_PORT}:55432
    depends_on:
        - labelbk
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - .:/home/node
    command: "yarn start:client:dev"
    stdin_open: true
